services:
  - type: web
    runtime: go
    name: drone-planner-api
    region: oregon
    buildCommand: cd server && go mod download && go build -o drone-planner-server
    startCommand: cd server && ./drone-planner-server
    envVars:
      - key: FRONTEND_URL
        value: https://drone-app-q23f.vercel.app
      - key: MONGODB_URI
        sync: false  # Set manually in Render dashboard
      - key: SUPABASE_JWT_SECRET
        sync: false  # Set manually in Render dashboard
      # Add other environment variables as needed
      # - key: API_KEY
      #   sync: false 